services:
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - "./todo-frontend/:/usr/src/app"
      - node_modules:/usr/src/app/node_modules
    restart: "no"

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - todo-frontend

volumes:
  node_modules: